"""'update'

Revision ID: 892aca2c26f3
Revises: 2a8adb47a810
Create Date: 2020-06-20 17:00:02.785908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892aca2c26f3'
down_revision = '2a8adb47a810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gpb_coin', sa.Integer(), nullable=True))
    op.drop_column('user', 'land_coin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('land_coin', sa.INTEGER(), nullable=True))
    op.drop_column('user', 'gpb_coin')
    # ### end Alembic commands ###
